dist: xenial
language: python
python:
  - '3.5'
  - '3.6'
  - '3.7'
env:
  - DJANGO_VERSION=2.2.1
  - DJANGO_VERSION=2.1.8
  - DJANGO_VERSION=1.11.20
install: 
- pip install Django==$DJANGO_VERSION pytest
- python setup.py install
script: py.test
